spring:
  application:
    name: g_51_security_jwt
  datasource:
    url: jdbc:postgresql://localhost:5433/g_51_security_jwt
    username: my_user
    password: pos1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: wNFuHjcqszGQdYqEYs7r/yMBJ8kIlWSpA6vX8asTA70=
  refresh: Sg7YpytnEVjB6gGN5IT6jKkC/0YDmDbo9vxYBt0Zm48=